<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.10.0-rc1 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id: setup.php 9697 2006-11-13 08:32:28Z nijel $
 * Date: Mon, 12 Feb 2007 21:37:12 GMT
 */

/* Servers configuration */
$i = 0;

/* Server db1 (cookie) */
$i++;
$cfg['Servers'][$i]['host'] = '10.0.0.200';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = true;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['verbose'] = 'db1';

/* End of servers configuration */

$cfg['ExecTimeLimit'] = 0;
$cfg['blowfish_secret'] = '45d0dcddc04c11.22852085';
$cfg['LeftFrameLight'] = true;
$cfg['LeftFrameDBTree'] = true;
$cfg['LeftFrameDBSeparator'] = '_';
$cfg['LeftFrameTableSeparator'] = '__';
$cfg['LeftFrameTableLevel'] = 1;
$cfg['LeftDisplayLogo'] = false;
$cfg['LeftDisplayServers'] = true;
$cfg['DisplayServersList'] = false;
$cfg['DisplayDatabasesList'] = false;
$cfg['LeftPointerEnable'] = true;
$cfg['ErrorIconic'] = false;
$cfg['MainPageIconic'] = false;
$cfg['ReplaceHelpImg'] = false;
$cfg['NavigationBarIconic'] = false;
$cfg['PropertiesIconic'] = false;
$cfg['DefaultTabServer'] = 'main.php';
$cfg['DefaultTabDatabase'] = 'db_structure.php';
$cfg['DefaultTabTable'] = 'sql.php';
$cfg['LightTabs'] = true;
$cfg['ForceSSL'] = true;
$cfg['ShowPhpInfo'] = true;
$cfg['ShowChgPassword'] = false;
$cfg['AllowArbitraryServer'] = false;
$cfg['LoginCookieValidity'] = 3600;
$cfg['PmaAbsoluteUri'] = 'https://team.4chan.org/developer/pma/';
$cfg['ThemeDefault'] = 'original';
?>
